select * from tbcliente;
SELECT DNI, NOMBRE, DIRECCION1, DIRECCION2, BARRIO, CIUDAD, ESTADO,CP,
 FECHA_NACIMIENTO, EDAD, SEXO, LIMITE_CREDITO, VOLUMEN_COMPRA, PRIMERA_COMPRA FROM tbcliente;
 
 SELECT  CIUDAD, NOMBRE, DNI, SEXO FROM tbcliente;
 
 SELECT NOMBRE AS Nombre_Completo, DNI AS Dni_numero FROM tbcliente;
 
 SELECT NOMBRE, SEXO, CIUDAD, DNI FROM tbcliente LIMIT 10;
 
 
 